# Generated by Django 3.2.6 on 2021-08-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pno',
        ),
    ]
